- id: veritensor-scan
  name: Veritensor AI Security Scanner
  description: Scans AI models, Notebooks, and RAG documents for malware and secrets.
  entry: veritensor scan
  language: python
  types: [file]
  files: \.(pt|pth|bin|pkl|ckpt|h5|keras|safetensors|gguf|ipynb|pdf|docx|md)$
  require_serial: true
